#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh"  # Loads all defined icons

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=37 blur_radius=30 color=$BAR_COLOR

# Calculate y_offset for vertical centering
BAR_HEIGHT=37
BACKGROUND_HEIGHT=26
Y_OFFSET=1


##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="SF Pro:Semibold:16.0"
  label.font="SF Pro:Semibold:15.0"
  icon.color=$WHITE
  label.color=$WHITE
  background.color=$ITEM_BG_COLOR
  background.corner_radius=12
  background.height=$BACKGROUND_HEIGHT
  y_offset=$Y_OFFSET
  icon.padding_left=10
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=10
)
sketchybar --default "${default[@]}"

# -- LEFT SIDE ITEMS --
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

sketchybar -m --add item yabai_mode left \
              --set yabai_mode update_freq=3 \
              --set yabai_mode script="~/.config/sketchybar/plugins/yabai_mode.sh" \
              --set yabai_mode click_script="~/.config/sketchybar/plugins/yabai_mode_click.sh" \
              --subscribe yabai_mode space_change

#sketchybar -m --add       item               yabai_float left                                                    \
              --add       event              window_focus                                                        \
              --add       event              float_change                                                        \
              --set       yabai_float        script="~/.config/sketchybar/plugins/yabai_float.sh"                \
                                             click_script="~/.config/sketchybar/plugins/yabai_float_click.sh"    \
                                             lazy=off                                                            \
              --subscribe yabai_float        front_app_switched window_focus float_change                        \



# -- RIGHT SIDE ITEMS --

# Sketchybar reload button
sketchybar --add item reload.bar right                                    \
           --set reload.bar                                               \
             icon=$RELOAD_ICON                                            \
             icon.padding_left=6                                          \
             icon.padding_right=6                                         \
             icon.align=center                                           \
             align=center                                                \
             background.corner_radius=50 \
             background.drawing=on                                        \
             click_script="$PLUGIN_DIR/reload_sketchybar.sh"              \
             label.drawing=off

# Clock
sketchybar --add item clock right                 \
           --set clock                            \
             icon=􀐫                               \
             label="Initial"                      \
             update_freq=1                        \
             script="$PLUGIN_DIR/clock.sh"        \                          \
             NAME=clock

# Calendar
sketchybar --add item calendar right             \
           --set calendar                        \
             icon=􀧞                              \
             label="Initial"                     \
             update_freq=1                       \
             script="$PLUGIN_DIR/calendar.sh"    \                      \
             NAME=calendar

# # WiFi widget configuration
# sketchybar --add item wifi right                   \
#            --set wifi script="$PLUGIN_DIR/wifi.sh"  \
#                      update_freq=2                  \
        
                    

source $ITEM_DIR/volume.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/media.sh



##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
